routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'home');

app/Http/Livewire/BetOption/BetOption.php
<?php

namespace App\Http\Livewire\BetOption;

use Livewire\Component;

class BetOption extends Component
{
  public $dice;
  public $betsAllowed;
  public $diceHaveBeenRolled;
  public $bet;
  public $pay;
  public $distribution = [];
  public $sum;
  public $big;
  public $small;

  // EVENT LISTENERS

  protected $listeners = ['diceRollCompleted', 'betOptionsCleared', 'betsProhibited'];

  public function diceRollCompleted($newDice)
  {
    $this->diceHaveBeenRolled = true;
    $this->pay = false;
    $this->distribution = [
      '1' => 0,
      '2' => 0,
      '3' => 0,
      '4' => 0,
      '5' => 0,
      '6' => 0
    ];

    $this->dice[0] = $newDice[0];
    $this->dice[1] = $newDice[1];
    $this->dice[2] = $newDice[2];
    $this->sum = $this->dice[0] + $this->dice[1] + $this->dice[2];
    foreach ($this->dice as $die) {
      $this->distribution[strval($die)]++;
    }
    $this->big = (($this->sum >= 11) && ($this->sum <= 17)) ? true : false;
    $this->small = (($this->sum >= 4) && ($this->sum <= 10)) ? true : false;
    $betOutcome = $this->determinePay();
    $this->emit('diceRollCompletedAndEvaluated', $betOutcome);
  }

  public function betOptionsCleared()
  {
    $this->init();
  }

  public function betsProhibited()
  {
    $this->betsAllowed = false;
  }

  // ACTIONS

  public function toggleBet()
  {
    if (!$this->betsAllowed) {
      return;
    }
    $this->bet = !$this->bet;
    $betsPlaced = $this->bet ? 1 : -1;
    $this->emit('betToggled', $betsPlaced);
  }

  // This method is overriden by each class that extends BetOption.
  public function determinePay()
  {
  }

  // LIFECYCLE HOOKS

  public function mount()
  {
    $this->init();
  }

  // PROTECTED FUNCTIONS

  protected function init()
  {
    $this->dice = [1, 1, 1];
    $this->betsAllowed = true;
    $this->diceHaveBeenRolled = false;
    $this->bet = false;
    $this->pay = false;
    $this->distribution = [
      '1' => 0,
      '2' => 0,
      '3' => 0,
      '4' => 0,
      '5' => 0,
      '6' => 0
    ];
    $this->sum = 0;
    $this->big = false;
    $this->small = false;
  }
}

resources/views/game.blade.php
<div class="container bg-brown-50 font-nunito_regular mx-auto px-16 pt-1 pb-1 mt-1 mb-4" x-show="show === 'game'">

  <!-- BIG / SMALL -->
  <div class="-mx-1 flex flex-wrap">

    <div class="flex flex-col p-1 w-1/3">
      @livewire('bet-option.small')
    </div>

    <div class="flex flex-col p-1 w-1/3 ">
      <div class="text-5xl font-nunito_bold text-brown-600 text-center leading-tight mx-5">
        {{ config('app.name', 'Laravel Application') }}
      </div>
      <div class="flex items-center w-full">
        <button class="bg-brown-300 text-amber-200 text-center font-nunito_bold rounded w-48 py-1 mx-auto"
          x-on:click="show = 'help'">
          HOW TO PLAY
        </button>
      </div>
    </div>

    <div class="flex flex-col p-1 w-1/3">
      @livewire('bet-option.big')
    </div>
  </div>

  <!-- DOUBLES AND TRIPLES -->
  <div class="-mx-1 flex flex-wrap">

    <div class="flex flex-col p-1 w-1/3">
      @include('subgrids.second-row-first')
    </div>

    <div class="flex flex-col p-1 w-1/3">
      @include('subgrids.second-row-second')
    </div>

    <div class="flex flex-col p-1 w-1/3">
      @include('subgrids.second-row-third')
    </div>
  </div>

  <!-- TOTALS -->
  <div class="-mx-1 flex flex-wrap">

    <div class="flex flex-col p-1 w-1/14">
      @livewire('bet-option.total-four')
    </div>

    <div class="flex flex-col p-1 w-1/14">
      @livewire('bet-option.total-five')
    </div>

    <div class="flex flex-col p-1 w-1/14">
      @livewire('bet-option.total-six')
    </div>

    <div class="flex flex-col p-1 w-1/14">
      @livewire('bet-option.total-seven')
    </div>

    <div class="flex flex-col p-1 w-1/14">
      @livewire('bet-option.total-eight')
    </div>

    <div class="flex flex-col p-1 w-1/14">
      @livewire('bet-option.total-nine')
    </div>

    <div class="flex flex-col p-1 w-1/14">
      @livewire('bet-option.total-ten')
    </div>

    <div class="flex flex-col p-1 w-1/14">
      @livewire('bet-option.total-eleven')
    </div>

    <div class="flex flex-col p-1 w-1/14">
      @livewire('bet-option.total-twelve')
    </div>

    <div class="flex flex-col p-1 w-1/14">
      @livewire('bet-option.total-thirteen')
    </div>

    <div class="flex flex-col p-1 w-1/14">
      @livewire('bet-option.total-fourteen')
    </div>

    <div class="flex flex-col p-1 w-1/14">
      @livewire('bet-option.total-fifteen')
    </div>

    <div class="flex flex-col p-1 w-1/14">
      @livewire('bet-option.total-sixteen')
    </div>

    <div class="flex flex-col p-1 w-1/14">
      @livewire('bet-option.total-seventeen')
    </div>
  </div>

  <!-- TOTALS -->
  <div class="-mx-1 flex flex-wrap">

    <div class="flex flex-col p-1 w-1/15">
      @livewire('bet-option.combo-one-two')
    </div>

    <div class="flex flex-col p-1 w-1/15">
      @livewire('bet-option.combo-one-three')
    </div>

    <div class="flex flex-col p-1 w-1/15">
      @livewire('bet-option.combo-one-four')
    </div>

    <div class="flex flex-col p-1 w-1/15">
      @livewire('bet-option.combo-one-five')
    </div>

    <div class="flex flex-col p-1 w-1/15">
      @livewire('bet-option.combo-one-six')
    </div>

    <div class="flex flex-col p-1 w-1/15">
      @livewire('bet-option.combo-two-three')
    </div>

    <div class="flex flex-col p-1 w-1/15">
      @livewire('bet-option.combo-two-four')
    </div>

    <div class="flex flex-col p-1 w-1/15">
      @livewire('bet-option.combo-two-five')
    </div>

    <div class="flex flex-col p-1 w-1/15">
      @livewire('bet-option.combo-two-six')
    </div>

    <div class="flex flex-col p-1 w-1/15">
      @livewire('bet-option.combo-three-four')
    </div>

    <div class="flex flex-col p-1 w-1/15">
      @livewire('bet-option.combo-three-five')
    </div>

    <div class="flex flex-col p-1 w-1/15">
      @livewire('bet-option.combo-three-six')
    </div>

    <div class="flex flex-col p-1 w-1/15">
      @livewire('bet-option.combo-four-five')
    </div>

    <div class="flex flex-col p-1 w-1/15">
      @livewire('bet-option.combo-four-six')
    </div>

    <div class="flex flex-col p-1 w-1/15">
      @livewire('bet-option.combo-five-six')
    </div>
  </div>

  <!-- SINGLES -->
  <div class="-mx-1 flex flex-wrap">

    <div class="flex flex-col p-1 w-1/6">
      @livewire('bet-option.single-one')
    </div>

    <div class="flex flex-col p-1 w-1/6">
      @livewire('bet-option.single-two')
    </div>

    <div class="flex flex-col p-1 w-1/6">
      @livewire('bet-option.single-three')
    </div>

    <div class="flex flex-col p-1 w-1/6">
      @livewire('bet-option.single-four')
    </div>

    <div class="flex flex-col p-1 w-1/6">
      @livewire('bet-option.single-five')
    </div>

    <div class="flex flex-col p-1 w-1/6">
      @livewire('bet-option.single-six')
    </div>
  </div>

  <div class="mt-1">
    @livewire('control')
  </div>
</div>

resources/views/help.blade.php
  <div class="container w-lg bg-white font-nunito_regular text-lg mx-auto px-64 my-4 py-6" x-show="show === 'help'">

    <div class="flex justify-center w-full mb-6">
      <button class="text-amber-900" x-on:click="show = 'game'">
        Return to the game
      </button>
    </div>

    <h2 class="text-4xl font-nunito_bold text-brown-600 text-center leading-tight mb-6">
      How to Play Sic Bo
    </h2>

    <p class="">
      Sic Bo is a simple gambling game where the player bets on the outcome of rolling 3 dice.
    </p>

    <p class="mt-6">
      The game proceeds as follows:
    </p>

    <ul class="mt-6 list-inside list-disc">
      <li class="">
        The player places his bets.
      </li>
      <li class="">
        The player rolls the dice.
      </li>
      <li class="">
        The score is adjusted based on the bets placed and the roll of the dice.
      </li>
      <li class="">
        Repeat the above steps.
      </li>
    </ul>

    <p class="mt-6">
      At the beginning of the game the board looks like this.
    </p>

    <div class="w-2/3 mx-auto mt-6">
      <img src="/img/game1.png" alt="Sic Bo board at the beginning of the game">
    </div>

    <p class="mt-6">
      <span class="font-nunito-bold text-amber-900">
        Step 1: Place your bets.
      </span>
      There are 50 choices on the board, each representing a possible outcome from rolling the dice. Click on a choice
      to place your bet. If you change your mind, click on it again and your bet will be removed. Place as many bets as
      you'd like.
    </p>

    <p class="mt-6">
      When you place a bet, your bet lights up in amber.
    </p>

    <p class="mt-6">
      The player wins when the rolled dice match their bet. In the game shown below, the player would win if the rolled
      dice contained on or more of the following:
    </p>

    <ul class="list-inside list-disc mt-6">
      <li>Double threes</li>
      <li>Double fours</li>
      <li>One and three</li>
      <li>One and four</li>
      <li>Four and five</li>
      <li>Four and six</li>
      <li>Three</li>
      <li>Four</li>
    </ul>

    <div class="w-2/3 mx-auto mt-6">
      <img src="/img/game1a.png" alt="Sic Bo board with bets placed">
    </div>

    <p class="mt-6">
      The SMALL bet pays when the total of all three dice is from 4 to 10.
    </p>

    <p class="mt-6">
      The BIG bet pays when the total of all three dice is from 11 to 17.
    </p>

    <div class="w-2/3 mx-auto mt-6">
      <img src="/img/game1b.png" alt="Sic Bo board with bets placed">
    </div>

    <p class="mt-6">
      There are fourteen squares across the middle of the board labeled 4 to 17. Betting on any of these wins if the
      total of all three dice matches the bet. The example below would pay if the total equals 8, 10 or 12.
    </p>

    <div class="w-2/3 mx-auto mt-6">
      <img src="/img/game1c.png" alt="Sic Bo board with bets placed">
    </div>

    <p class="mt-6">
      The payoff for each bet is shown along with your bet. For example, a winning bet on one of the doubles returns 10
      points for every point bet. A winning bet on one of the triples returns 180 points for every point bet.
    </p>

    <p class="mt-6">
      In our example game, we've placed 12 bets and the board looks like this:
    </p>

    <div class="w-2/3 mx-auto mt-6">
      <img src="/img/game1x.png" alt="Sic Bo board with bets placed">
    </div>

    <p class="mt-6">
      <span class="font-nunito-bold text-amber-900">
        Step 2: Roll the dice.
      </span>
      The button is in the bottom right corner, next to the dice.
    </p>

    <div class="w-2/3 mx-auto mt-6">
      <img src="/img/game2.png" alt="Sic Bo board with button for rolling the dice">
    </div>

    <p class="mt-6">
      <span class="font-nunito-bold text-amber-900">
        Step 3: See the results.
      </span>
      Winning bets turn green, and losing bets are red.
    </p>

    <div class="w-2/3 mx-auto mt-6">
      <img src="/img/game3.png" alt="Sic Bo board showing winning and losing bets">
    </div>

    <p class="mt-6">
      <span class="font-nunito-bold text-amber-900">
        Check your new score.
      </span>
      Your new score is in the bottom left corner. The line above shows how your scrore was calculated, based on your
      wagers and the payoffs from your winning bets.
    </p>

    <div class="w-2/3 mx-auto mt-6">
      <img src="/img/game3a.png" alt="Sic Bo board showing winning and losing bets">
    </div>

    <p class="mt-6">
      <span class="font-nunito-bold text-amber-900">
        Place your next bets.
      </span>
      When the game starts, you are wagering 1 point for each bet you place. But you can increase your bet using the
      change bet buttons: Bet 2, Bet 3, Bet 4, or Bet 5.
    </p>

    <p class="mt-6">
      If you want to keep your bets from the last round, then just click Roll the Dice.
    </p>

    <p class="mt-6">
      If you want to start all over with new bets, click Clear Bets.
    </p>

    <p class="mt-6">
      Or you can click individual boxes to add and remove bets one at a time.
    </p>

    <div class="w-2/3 mx-auto mt-6">
      <img src="/img/game3b.png" alt="Sic Bo board showing winning and losing bets">
    </div>

    <div class="flex justify-center w-full mt-6">
      <button class="text-amber-900" x-on:click="show = 'game'">
        Return to the game
      </button>
    </div>

  </div>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

  <div x-data="{ show : 'game' }">

    @include('game')

    @include('help')

  </div>

@endsection